var mod = {};

mod.thopterFacts = [
    "Though not always the most efficient mode of transport, thopters are widely agreed to be the cutest. Other cute modes of transport include mini-trains, roto-copters, and camels.",
    "There exist a wide variety of safe practices that can help your servo or thopter function happily in its new role.",
    "Since servo and thopter directions are imprinted at creation, it is recommended that artificers assist your constructs in adapting.",
    "The Consulate banned the use of kitchen thopters after what came to be known as The Grand Conflagration, about three years ago.",
    "There is an ongoing linguistic debate over whether the sound of a thopter’s wing is “thop” or “thwop”.",
    "A common misconception is that thopters enter hibernation in the spring. This is untrue, as thopters do not require sleep.",
    "Did you know: to protect its citizens from incendiary dangers, the Consulate has deployed 36% more thopters than last week.",
    "Thank you for your patience. We now return this network to its regularly-scheduled pieces of thopter trivia",
    "Though a popular engineering experiment, pedal-powered thopters rarely more than slow a fatal descent.",
    "The motion of thopter wings can be used for a wide variety of applications, such as cooling pies.",
    "If you see thopters bristling with blade attachments, these are harvesting thopters crossing through the city on their way to another farm.",
    "The proper term for a damaged thopter in a death-spiral is “tragedy”, as in, “Look at that tragedy, a poor thopter is no more.”",
    "The Consulate has begun its yearly technology census, and requests that citizens state the quantity, sizes, and styles of their thopters.",
    "To remain safe in thopter-heavy environments, consider ducking.",
    "For citizens concerned about the recent uptick in thopter deployment, this is simply a routine test of Consulate thopter networks.",
    "When adding filigree and other ornamentation to your thopters, recall that thopters are intended to be capable of flight.",
    "Thanks to fumigation thopters, Ghirapur has been free of gremlin infestations for almost half a year!",
    "Without Consulate funding, the aether required to power the average thopter would cost approximately 7 times more.",
    "Famed eccentric artificer Kolis Derava wrote an essay detailing 57 thopter construction methods. Upon inspection, only 2 of them could fly.",
    "Stunt thopters are sometimes fitted with aether propulsion systems to assist them through maneuvers. Without such systems, loops and spectacular aether-infused crashes would surely be impossible.",
    "Famed eccentric artificer Kolis Derava once claimed to have created completely organic thopters. They were, upon closer inspection, flies.",
    "Ghirapur inventors are currently working on an on-demand thopter transport system called “Thöpper”. These inventors were unavailable for comment to explain what those two little dots are, or where they came from.",
    "Many panharmonica can play ambient noise to soothe you to sleep; the most popular choice of sound is the gentle “thop” of a thopter’s wings.",
    "The Consulate recommends oiling your thopters once a week, and cooing gently to them at least once a day.",
    "If you forget the components necessary to construct a thopter, just use the C.O.G.W.E.L.L. mnemonic. C.O.G.W.E.L.L. stands for Chassis, Orbiter, Gears, Wings, Energy, Lead, and License. Filigree, while optional, is highly recommended.",
    "Even the most basic thopters have at least three built-in commands: “stay”, “go”, and “flutter adorably.”",
    "Common thopter wing materials include: polyaetheride, aetherflex, inderasaeth, and camel leather.",
    "Some of Ghirapur’s richest citizens employ entire squadrons of thopters for the purpose of conveying mixed drinks during parties.",
    "Demolition thopters function as miniature bombers, dropping their payload from altitude. This maneuver is known as a “thop ‘n’ drop.”. A demolition thopter that fails to release its payload is called a “non-drop-thop.”. The similarity of these terms has caused considerable confusion in the demolition industry, and at least two reported casualties.",
    "One in three mass-produced thopters are unfit for duty. To maintain this average, some thopters are smashed following production.",
    "When constructing thopters, remember this mnemonic: grease twice, cut once, disassemble never. ",
    "Artificer Raj Hanar reportedly broke the record for smallest thopter, but can’t seem to find his invention.",
    "When securing your thopter for ground transport, secure the wings in an upright and locked position, and fully tighten all wingnuts",
    "If you believe that a Consul thopter is tailing you, worry not! Consul thopters are absolutely not intended to spy on you.",
    "When attempting to hail a transport thopter, it is recommended that you wave your arms over your head in the most foolish possible manner.",
    "The proper plural term for a connection of thopters is “thopton”, e.g. “A thopton of thopters just cut me off!”",
    "While servos are the ubiquitous machine, thopters are widely regarded as superior, and prettier to look upon. In more common terms, thopters are to servos as Pashtur Cruisers are to half-baked dragsters.",
    "Over 6,077,363 thopters have been piloted into Ghirapur thus far during the Inventors’ Fair, with a mere 28% casualty rate! If this trend continues, it will be a record low for Inventors’ Fair destruction of winged constructs."
];

mod.servoFacts = [
    "Factory Servos are built with a tracking device so that, if stolen or missing, they can be located. This feature is rarely, if ever, used.",
    "If Servos were considered alive, they would then have the opportunity to gain more rights as Kaladeshi denizens, such as the right to vote. Voting rights are given to all living constructs in Kaladesh. Regulating which constructs were sapient prooved too cumbersome. However, choosing which constructs were considered legally alive proved to be an effective alternative.",
    "Servos can come in a variety of standardized designs. However, while personal repair and modification is discouraged, it is not yet illegal.",
    "If a Servo was ever to use a Consul weapon without orders, a small explosive device implanted in side the Servo would detonate. It's messy.",
    "Servos that are used in combat are at least 20% less likely to be destroyed by their owners than stay-at-home Servos. ",
    "Servos are often used to pilot Skysovereign when on skeleton crew. Its weapons, however, are still manned by trained Consul operatives 24/7.",
    "All factory Servos have a 24 hour limited warranty. If your new Servo arrives broken, incineration and replacement are free of charge.",
    "It takes exactly 2.5 Servos to change a lightbulb. Or at least the sum parts of 2.5 Servos.",
    "Destruction of Consul property AND aiding a fugitive are both punishable offences. However, yes, that is physically possible.",
    "While Servos do not experience pain, they can experience fear. However, they are unable to express this fear in any meaningful way.",
    "Servo encryption software is very cheap in order to manage the cost of production. Please do not store sensitive information inside Servos.",
    "Simply remove its optical sensors. Servos don't feel pain, so the procedure is literally painless.",
    "Piloting Servos are considered as the machinery driving itself, and are often used as a poorman‘s alternative to Fleetwheel-class vehicles.",
    "Servo Incineration Facilities are conveniently located on nearly every block throughout the city of Ghiripur. Often nextdoor to coffee shops",
    "Servos can occasionally discharge excess Aether as a viscous fluid. Do not touch this fluid unprotected under any circumstances.",
    "Weaponized servos are only a threat to enemies of the state. They will not harm law-abiding citizens unless provoked.",
    "Some success has been found in attaching Servos to powerful weapons. This is outweighed by the fact that these Servos easily tip over.",
    "Inventors use Servos to crash test new, experimental vehicles. A test is successful if the Servo can survive being flung from the wreckage. Most vehicles go through about 20 or 30 tests before one is considered successful.",
    "While it is encouraged to have your malfunctioning Servos scrapped, many small business have arisen to offer Servo repair and customization. This is caused by a Servos programming inherently rejecting modifications, and so crafty inventors can sell modified Servos at a high price.",
    "Servos have no sense of smell or taste, rendering them oblivious to the popularity of autumnal-flavored food and drinks. ",
    "When 2 Servos are created simultaneously, they think of each other as \"siblings.\" An incorrect idea, as Servos have no capacity for family.",
    "Servos are an important source of food for Gremlins, as they are full of Aether, easy to catch, and are rarely missed. ",
    "With patience, Servos can be trained to do basic tricks, such as jump, roll over, and fetch, though Play Dead comes easiest to most Servos.",
    "The monetary value of scrap Servos fluctuates based on supply vs demand. Currently the exchange rate is high, so now is a good time to sell!",
    "Currently, the oldest Servo is 16 months old, kept in the care of Head Judge Tezzeret. He keeps it as a pet named Nic Jr.",
    "Servos enter a sleep mode when left alone for more than an hour. It's unknown if this is to conserve energy or if they cant bear loneliness.",
    "Servos made from softer, heavier metals like gold are made for the wealthy to gawk at, as their legs tend to collapse under their own weight",
    "These Constructs refer to their creations as \"children\" despite holding similar apathy towards their Servos.",
    "Some Constructs have been seen to produce Servos of their very own, a practice some believe to be a threat to organic life. ",
    "85% of these Servos were named Eustace.",
    "Servos make very popular children's gifts. 65% of all scrap Servos were destroyed/mangled by children they were given to.  ",
    "At one time, Servos communicated using a complex series of chirps & whistles. Since that was too cute, they now sound like an alarm clock.",
    "An artificer can use a Servo to improve their combat potential. This destroys the Servo, but since they're not legally alive, no one cares!",
    "While considered disposable, Servos are actually self aware, and have complicated thoughts and feelings.  ",
    "Amongst them selves, Servos are often named Eustace. Most people choose not to acknowledge this fact.  ",
    "Any & all Servos that were submitted to the Inventors Fair were summarily rejected. You don't need to reinvent the gear, idiot. ",
    "Some Servos have been reported expressing love to their owners. Please know that this is a glitch and that the Servo needs to be terminated.",
    "The main push-back against Servos being considered \"alive\" comes from the Consul refusing to deal in such petty matters as \"moral quandary\".",
    "The 1st Servo was invented at the start of the Aether Boom. The 2nd Servo was made from its scraps shortly after the 1st one learned speech.",
    "Servos have about as much computational brain function as a human infant. Or a monkey, depending on what makes you less uncomfortable.",
    "Thopters whose wings have been damaged are in a legal grey area. They become similar to Servos, but still are legally considered alive.",
    "Many Servos are very insect-like in form, and some mistakenly get destroyed out of fright. Like with insects, no remorse is felt afterwards.",
    "Servos have no recognized form of communication, as they have no speech module, but this hasn't stopped some from trying to be understood.",
    "Thopters were given the legal right to life after it was discovered that they were much harder to mass produce than Servos. ",
    "Thopters, while similar to them in many respects, are importantly distinct from Servos, in that they are instead legally considered alive.",
    "It is a common, if ultimately meaningless practice for Servos to be named by their owners. Common Servo names include: Bartholomew, Gizmo, Thomas, Rachel, Sarah, and \"it / that thing\"",
    "Rarely, small social movements protested to make the Consulate legally declare Servos \"alive\". Subsequent arrests usually put an end to it.",
    "Servos come in a variety of shapes, sizes and styles. This means that Servos are often discriminated against. Not all Servos deserve love.",
    "It takes approx. 1.21 Kg. of metal and 3 units of Aether to create a Servo. Conveniently, crushing one yields the the exact same quantities.",
    "Artificers have had success enouling some Servos. These Servos are still not legally considered alive. ",
    "Servos are allowed to be used in Ovalchase Racing Events as vehicle pilots, despite Servos causing just as many, if not more, fatal crashes.",
    "Servos used as household appliances have a 85% higher chance of spontaneously self-destructing than Servos used in the Ovalchase Races.",
    "Servos were then programmed to not feel anything once Servos started experiencing bliss as pain. This average is found as the mean between Servos being destroyed immediately after creation and Servos working as household appliances.",
    "Servos were originally programmed to feel pain when damaged. This was quickly changed to have them feel bliss when damaged. ",
    "Once a Servo is rendered inoperable, it is melted down, to be reshaped into other servos. We understand that modern Servos feel no pain.",
    "The average \"life\" span of a Servo is about 20 minutes, though there has been no record of a Servo malfunctioning without outside influence."
];

module.exports = mod;